package MobileShop.Common;

import org.springframework.stereotype.Component;

@Component
public class BodySendMail {

	public String sendMailVerification(String fullname, String code) {
		String body = 
				"<!DOCTYPE html>\r\n"
				+ "<html>\r\n"
				+ "\r\n"
				+ "<head>\r\n"
				+ "  <title>Movie Tickets - Code With Bishal</title>\r\n"
				+ "  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css\" />\r\n"
				+ "  <style>\r\n"
				+ "    body {\r\n"
				+ "      margin: 0;\r\n"
				+ "      padding: 0;\r\n"
				+ "      font-family: 'Poppins', sans-serif;\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    .movie_card {\r\n"
				+ "      color: #fff;\r\n"
				+ "      height: 390px;\r\n"
				+ "      margin: 50px auto;\r\n"
				+ "      display: flex;\r\n"
				+ "      max-width: 100%;\r\n"
				+ "      background: linear-gradient(#373B44, #4286f4);\r\n"
				+ "      box-shadow: 0 0 40px rgba(0, 0, 0, 0.3);\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    .left {\r\n"
				+ "      width: 100%;\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    .datails {\r\n"
				+ "      width: 90%;\r\n"
				+ "      padding: 30px;\r\n"
				+ "      margin-top: -25px;\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    .c_right img {\r\n"
				+ "      height: 390px;\r\n"
				+ "      width: 100%;\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    .head {\r\n"
				+ "      width: 100%;\r\n"
				+ "      display: flex;\r\n"
				+ "      justify-content: center;\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    .rated,\r\n"
				+ "    .year,\r\n"
				+ "    .genre,\r\n"
				+ "    .time {\r\n"
				+ "      color: #fff;\r\n"
				+ "      padding: 10px;\r\n"
				+ "      font-weight: bold;\r\n"
				+ "      border-radius: 15px;\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    .rated {\r\n"
				+ "      box-shadow: 0 0 50px rgba(0, 0, 0, 0.568);\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    a {\r\n"
				+ "      color: black;\r\n"
				+ "      display: block;\r\n"
				+ "      text-decoration: none;\r\n"
				+ "      outline: none;\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    .buttons {\r\n"
				+ "      margin-left: -10px;\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    button,\r\n"
				+ "    .rated,\r\n"
				+ "    .play_btn {\r\n"
				+ "      background: linear-gradient(#b24591c9, #f15f7ac4);\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    button {\r\n"
				+ "      color: #fff;\r\n"
				+ "      border: none;\r\n"
				+ "      padding: 20px;\r\n"
				+ "      outline: none;\r\n"
				+ "      font-size: 12px;\r\n"
				+ "      margin-top: 30px;\r\n"
				+ "      margin-left: 5px;\r\n"
				+ "      border-radius: 12px;\r\n"
				+ "      box-shadow: 0 0 20px rgba(0, 0, 0, 0.616);\r\n"
				+ "      cursor: pointer;\r\n"
				+ "      transition: 200ms ease-in-out;\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    button:hover {\r\n"
				+ "      transform: scale(1.1);\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    .play_btn {\r\n"
				+ "      height: 100%;\r\n"
				+ "      margin: -394px auto;\r\n"
				+ "      position: relative;\r\n"
				+ "      text-align: center;\r\n"
				+ "      background: linear-gradient(#fc5c7c65, #6a82fb5b);\r\n"
				+ "      box-shadow: 0 0 50px rgba(0, 0, 0, 0.2);\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    .fa-play-circle {\r\n"
				+ "      color: black;\r\n"
				+ "      font-size: 160px;\r\n"
				+ "      margin-top: 110px;\r\n"
				+ "      animation: bounce 1s infinite;\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    .c_right:hover {\r\n"
				+ "      cursor: pointer;\r\n"
				+ "      transform: scale(1.1);\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    .credits {\r\n"
				+ "      font-size: 20px;\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    @keyframes bounce {\r\n"
				+ "      from {\r\n"
				+ "        opacity: 1;\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      to {\r\n"
				+ "        opacity: 0;\r\n"
				+ "      }\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    @media (max-width: 700px) {\r\n"
				+ "      .movie_card {\r\n"
				+ "        display: block;\r\n"
				+ "      }\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    @media (max-width: 600px) {\r\n"
				+ "      button {\r\n"
				+ "        display: none;\r\n"
				+ "      }\r\n"
				+ "    }\r\n"
				+ "  </style>\r\n"
				+ "</head>\r\n"
				+ "\r\n"
				+ "<body>\r\n"
				+ "  <div class=\"wrapper\">\r\n"
				+ "    <div class=\"movie_card\">\r\n"
				+ "      <div class=\"left\">\r\n"
				+ "        <div class=\"datails\">\r\n"
				+ "          <h1 style=\"text-align: center;\">Xác Minh Tài Khoản Sneat</h1>\r\n"
				+ "          <p style=\"color: rgb(251, 250, 250); font-size: 20px; font-weight: bolder;\">Xin chào, "+fullname+"!</p>\r\n"
				+ "          <p class=\"description\">Chúng tôi nhận được yêu cầu xác minh tài khoản Sneat của bạn. Để hoàn tất việc xác minh tài khoản, vui lòng nhập mã xác nhận sau đây:</p>\r\n"
				+ "          <div class=\"head\">\r\n"
				+ "            <p class=\"rated\">"+code+"</p>\r\n"
				+ "          </div>\r\n"
				+ "          <p class=\"description\"> <strong style=\"color: yellow;\">Lưu ý: Không chia sẻ mã này với bất kỳ ai để đảm bảo tài khoản của bạn được an toàn.</strong> Sau khi hoàn tất việc xác minh tài khoản, bạn có thể truy cập vào tài khoản của mình. Cảm ơn bạn đã lựa chọn Sneat, chúc bạn có những trải nghiệm tuyệt vời.</p>\r\n"
				+ "        </div>\r\n"
				+ "      </div>\r\n"
				+ "    </div>\r\n"
				+ "  </div>\r\n"
				+ "</body>\r\n"
				+ "\r\n"
				+ "</html>";
		return body;
	}
	
	public String sendMailForgotPassword(String fullname, String password) {
		String body = 
				"<!DOCTYPE html>\r\n"
				+ "<html>\r\n"
				+ "\r\n"
				+ "<head>\r\n"
				+ "  <title>Movie Tickets - Code With Bishal</title>\r\n"
				+ "  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css\" />\r\n"
				+ "  <style>\r\n"
				+ "    body {\r\n"
				+ "      margin: 0;\r\n"
				+ "      padding: 0;\r\n"
				+ "      font-family: 'Poppins', sans-serif;\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    .movie_card {\r\n"
				+ "      color: #fff;\r\n"
				+ "      height: 390px;\r\n"
				+ "      margin: 50px auto;\r\n"
				+ "      display: flex;\r\n"
				+ "      max-width: 100%;\r\n"
				+ "      background: linear-gradient(#373B44, #4286f4);\r\n"
				+ "      box-shadow: 0 0 40px rgba(0, 0, 0, 0.3);\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    .left {\r\n"
				+ "      width: 100%;\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    .datails {\r\n"
				+ "      width: 90%;\r\n"
				+ "      padding: 30px;\r\n"
				+ "      margin-top: -25px;\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    .c_right img {\r\n"
				+ "      height: 390px;\r\n"
				+ "      width: 100%;\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    .head {\r\n"
				+ "      width: 100%;\r\n"
				+ "      display: flex;\r\n"
				+ "      justify-content: center;\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    .rated,\r\n"
				+ "    .year,\r\n"
				+ "    .genre,\r\n"
				+ "    .time {\r\n"
				+ "      color: #fff;\r\n"
				+ "      padding: 10px;\r\n"
				+ "      font-weight: bold;\r\n"
				+ "      border-radius: 15px;\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    .rated {\r\n"
				+ "      box-shadow: 0 0 50px rgba(0, 0, 0, 0.568);\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    a {\r\n"
				+ "      color: black;\r\n"
				+ "      display: block;\r\n"
				+ "      text-decoration: none;\r\n"
				+ "      outline: none;\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    .buttons {\r\n"
				+ "      margin-left: -10px;\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    button,\r\n"
				+ "    .rated,\r\n"
				+ "    .play_btn {\r\n"
				+ "      background: linear-gradient(#b24591c9, #f15f7ac4);\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    button {\r\n"
				+ "      color: #fff;\r\n"
				+ "      border: none;\r\n"
				+ "      padding: 20px;\r\n"
				+ "      outline: none;\r\n"
				+ "      font-size: 12px;\r\n"
				+ "      margin-top: 30px;\r\n"
				+ "      margin-left: 5px;\r\n"
				+ "      border-radius: 12px;\r\n"
				+ "      box-shadow: 0 0 20px rgba(0, 0, 0, 0.616);\r\n"
				+ "      cursor: pointer;\r\n"
				+ "      transition: 200ms ease-in-out;\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    button:hover {\r\n"
				+ "      transform: scale(1.1);\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    .play_btn {\r\n"
				+ "      height: 100%;\r\n"
				+ "      margin: -394px auto;\r\n"
				+ "      position: relative;\r\n"
				+ "      text-align: center;\r\n"
				+ "      background: linear-gradient(#fc5c7c65, #6a82fb5b);\r\n"
				+ "      box-shadow: 0 0 50px rgba(0, 0, 0, 0.2);\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    .fa-play-circle {\r\n"
				+ "      color: black;\r\n"
				+ "      font-size: 160px;\r\n"
				+ "      margin-top: 110px;\r\n"
				+ "      animation: bounce 1s infinite;\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    .c_right:hover {\r\n"
				+ "      cursor: pointer;\r\n"
				+ "      transform: scale(1.1);\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    .credits {\r\n"
				+ "      font-size: 20px;\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    @keyframes bounce {\r\n"
				+ "      from {\r\n"
				+ "        opacity: 1;\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      to {\r\n"
				+ "        opacity: 0;\r\n"
				+ "      }\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    @media (max-width: 700px) {\r\n"
				+ "      .movie_card {\r\n"
				+ "        display: block;\r\n"
				+ "      }\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    @media (max-width: 600px) {\r\n"
				+ "      button {\r\n"
				+ "        display: none;\r\n"
				+ "      }\r\n"
				+ "    }\r\n"
				+ "  </style>\r\n"
				+ "</head>\r\n"
				+ "\r\n"
				+ "<body>\r\n"
				+ "  <div class=\"wrapper\">\r\n"
				+ "    <div class=\"movie_card\">\r\n"
				+ "      <div class=\"left\">\r\n"
				+ "        <div class=\"datails\">\r\n"
				+ "          <h1 style=\"text-align: center;\">Quên Mật Khẩu Tài Khoản Sneat</h1>\r\n"
				+ "          <p style=\"color: rgb(251, 250, 250); font-size: 20px; font-weight: bolder;\">Xin chào, "+fullname+"!</p>\r\n"
				+ "          <p class=\"description\">Chúng tôi nhận được yêu cầu quên mật khẩu tài khoản Sneat của bạn. Chúng tôi đã thực hiện reset mật khẩu theo yêu cầu của bạn. Dưới đây là mật khẩu mới cho tài khoản Sneat của bạn:</p>\r\n"
				+ "          <div class=\"head\">\r\n"
				+ "            <p class=\"rated\">"+password+"</p>\r\n"
				+ "          </div>\r\n"
				+ "          <p class=\"description\"> <strong style=\"color: yellow;\">Lưu ý: Không chia sẻ mật khẩu này với bất kỳ ai để đảm bảo tài khoản của bạn được an toàn.</strong> Bạn có thể truy cập vào tài khoản của mình bằng mật khẩu mới này. Cảm ơn bạn đã lựa chọn Sneat, chúc bạn có những trải nghiệm tuyệt vời.</p>\r\n"
				+ "        </div>\r\n"
				+ "      </div>\r\n"
				+ "    </div>\r\n"
				+ "  </div>\r\n"
				+ "</body>\r\n"
				+ "\r\n"
				+ "</html>";
		return body;
	}
	
}
